services:
  postgres:
    image: postgres:13
    container_name: postgres-api
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: quarkus_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_api_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-api
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_app
      QUARKUS_DATASOURCE_USERNAME: sonar
      QUARKUS_DATASOURCE_PASSWORD: sonar
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_api_data: